[package]
name = "csv-explorer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
polars = { version = "0.50.0", features = ["lazy", "json"] }
qsv-sniffer = "0.11.0"
